before_script:
  - curl https://gitlab.mittwald.it/snippets/10/raw | bash

cache:
  paths:
    - node_modules/

typescript-compile:
  image: node:10.16
  stage: build
  script:
    - yarn compile

tslint:
  image: node:10.16
  stage: test
  script:
    - yarn lint

jest:
  image: node:10.16
  stage: test
  services:
    - vault
  variables:
    VAULT_ADDR: "http://vault:8200"
    VAULT_TOKEN: "test"
    VAULT_DEV_ROOT_TOKEN_ID: "test"
  script:
    - "curl -H 'X-Vault-Token: ${VAULT_DEV_ROOT_TOKEN_ID}' -X POST -d '{\"type\":\"transit\"}' http://vault:8200/v1/sys/mounts/transit"
    - yarn compile
    - yarn test

registry-publish:
  stage: deploy
  image: node:10.16
  script:
    - npm version from-git
    - yarn compile
    - cd dist/
    - npm publish
  only:
    - tags
