before_script:
  - curl https://gitlab.mittwald.it/snippets/10/raw | bash

cache:
  paths:
    - node_modules/

typescript-compile:
  image: node:10.16
  stage: build
  script:
    - yarn compile

tslint:
  image: node:10.16
  stage: test
  script:
    - yarn lint

jest:
  image: node:10.16
  stage: test
  services:
    - name: vault
      command: [
        "sh",
        "-c",
        "(while ! nc -z 127.0.0.1 8200; \
          do \
            sleep 1; \
            echo 'waiting for vault service ...'; \
          done; \
          vault secrets enable transit \
        ) & vault server -dev -dev-listen-address=0.0.0.0:8200"
      ]
  variables:
    VAULT_ADDR: "http://vault:8200"
    VAULT_TOKEN: "test"
    VAULT_DEV_ROOT_TOKEN_ID: "test"
  script:
    - while ! nc -z vault 8200; do sleep 0.5; done;
    - yarn compile
    - yarn test

registry-publish:
  stage: deploy
  image: node:10.16
  script:
    - npm version from-git
    - yarn compile
    - cd dist/
    - npm publish
  only:
    - tags
